"""Export a project version as a downloadable ZIP codebase."""

import io
import zipfile
from pathlib import Path

from sqlalchemy.ext.asyncio import AsyncSession

from ..models import Project, ProjectVersion


def build_site_zip(project: Project, version: ProjectVersion) -> bytes:
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{project.name}</title>
  <style>
{version.css or ""}
  </style>
</head>
<body>
{version.html or ""}
  <script>
{version.js or ""}
  </script>
</body>
</html>"""
        zf.writestr("index.html", html)
        zf.writestr("style.css", version.css or "")
        zf.writestr("app.js", version.js or "")
        if version.backend:
            for filename, content in version.backend.items():
                zf.writestr(f"backend/{Path(filename).name}", content)
        if version.db_schema:
            zf.writestr("schema.sql", version.db_schema)
        readme = f"""# {project.name}

Generated by HydraWeb.

- index.html — the site
- style.css — styles
- app.js — interactivity
- backend/ — FastAPI backend (if generated)
- schema.sql — PostgreSQL schema (if generated)
"""
        zf.writestr("README.md", readme)
    return buf.getvalue()


def build_zip_bytes(project: Project, version: ProjectVersion) -> bytes:
    return build_site_zip(project, version)
